# Day 28
 - Data Exploration
 - correlation , covariance

```2 ota or more variable ko relation (Dependent kati cha herni ho)```
```Study time vs result = high/low/medium```

In [2]:
import pandas as pd

In [4]:
titanic_df = pd.read_csv("titanic.csv")

In [5]:
titanic_df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
titanic_df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [7]:
titanic_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     889 non-null    str
dtypes: float64(2), int64(5), str(5)
memory usage: 83.7 KB

In [9]:
titanic_df.loc[1:1]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

In [12]:
titanic_df.value_counts("Survived")

Survived
0    549
1    342
Name: count, dtype: int64

In [14]:
titanic_df.value_counts("Sex")

Sex
male      577
female    314
Name: count, dtype: int64

In [ ]:
# Normalization of data

titanic_df.value_counts(["Sex", "Survived"])

Sex     Survived
male    0           468
female  1           233
male    1           109
female  0            81
Name: count, dtype: int64

In [18]:
titanic_df.value_counts(["Sex", "Survived"] , normalize= True , ascending=True)
# normalize ley chai 0 - 1 ko range ma value dinxa ( number of count / number of total count)

Sex     Survived
female  0           0.090909
male    1           0.122334
female  1           0.261504
male    0           0.525253
Name: proportion, dtype: float64

In [27]:
titanic_df[titanic_df["Sex"] == "female"]["Survived"].value_counts(ascending=True , normalize=True)

Survived
0    0.257962
1    0.742038
Name: proportion, dtype: float64

In [33]:
titanic_df[["Age","Fare"]].mean()

Age     29.699118
Fare    32.204208
dtype: float64

In [35]:
titanic_df[["Age", "Fare"]].median()

Age     28.0000
Fare    14.4542
dtype: float64

In [36]:
# Group by liyera mean nikalni

titanic_df.groupby(['Embarked', 'Survived']).mean(numeric_only=True)

                   PassengerId    Pclass        Age     SibSp     Parch  \
Embarked Survived
C        0          409.853333  2.200000  33.666667  0.253333  0.253333
         1          473.989247  1.634409  28.973671  0.494624  0.451613
Q        0          480.404255  2.936170  30.325000  0.510638  0.276596
         1          319.966667  2.866667  22.500000  0.300000  0.000000
S        0          449.868852  2.545667  30.203966  0.611241  0.348946
         1          448.857143  1.967742  28.113184  0.493088  0.539171

                        Fare
Embarked Survived
C        0         35.443335
         1         79.720926
Q        0         13.335904
         1         13.182227
S        0         20.743987
         1         39.547081

In [ ]:
# Covariance 
titanic_df[["Age" , "Fare"]].cov()

             Age         Fare
Age   211.019125    73.849030
Fare   73.849030  2469.436846