# Day27
- Pandas

In [21]:
import pandas as pd

a = [ '1' , '2 ' , '3' , '4 ' , '5']
res = pd.Series(a , index=['a' , 'b' , 'c' , 'd' , 'e' , ] )
res

a     1
b    2
c     3
d    4
e     5
dtype: str

In [30]:
dic = {
    id: 1,
    'Name': 'Sanjay',
    'State' : 'Bagmati',
    'Age': 25
}

res_dict = pd.Series(dic)
df = pd.DataFrame(dic , index=[1])
res_dict
df

   <built-in function id>    Name    State  Age
1                       1  Sanjay  Bagmati   25

In [23]:
# rows and columns ko combination lai Dataframe vanxa
# simple data frame

data = [['python' , 'java' , 'javascript' , 'C++']]
df = pd.DataFrame(data, index=['1'], columns=['Lang1', 'Lang2', 'Lang3', 'Lang4'])
print(df)

    Lang1 Lang2       Lang3 Lang4
1  python  java  javascript   C++

In [24]:

data = ['python' , 'java' , 'javascript' , 'C++']
df = pd.DataFrame(data , index=['1' , '2' , '3' , '4' ] , columns=['Language'])
df

     Language
1      python
2        java
3  javascript
4         C++

In [ ]:
# dictionary data frame

dict_data = {
    'Name': ['Sanjay' , 'Shishir' , 'Sujan'],
    'marks' : [89 , 90 , 92]
}
df = pd.DataFrame(dict_data)
df

      Name  marks
0   Sanjay     89
1  Shishir     90
2    Sujan     92

In [32]:
data = [
    ['python' , 'java' , 'javascript' , 'C++'], 
    ['C' , 'c#' , 'Kotlin', 'Go']
]

df = pd.DataFrame(
    data, 
    index=['1', '2'], 
    columns=['Lang 1', 'Lang 2', 'Lang 3', 'Lang 4']
)

print(df)

   Lang 1 Lang 2      Lang 3 Lang 4
1  python   java  javascript    C++
2       C     c#      Kotlin     Go

In [39]:
df['Name']

0     Sanjay
1    Shishir
2      Sujan
Name: Name, dtype: str

In [ ]:

# import gdown
# import pandas as pd
# file_id = "1pP0XwLrvXGIv3uEXKuc9Ug59soukErEI"
# url = f"https://drive.google.com/uc?id={file_id}"

gdown.download(url, "data.csv", quiet=False)
df = pd.read_csv("data.csv")
df.head()

/home/meteora/dsml-11/.venv/lib/python3.14/site-packages/gdown/download.py:42: XMLParsedAsHTMLWarning: It looks like you're using an HTML parser to parse an XML document.

Assuming this really is an XML document, what you're doing might work, but you should know that using an XML parser will be more reliable. To parse this document as XML, make sure you have the Python package 'lxml' installed, and pass the keyword argument `features="xml"` into the BeautifulSoup constructor.

If you want or need to use an HTML parser on this document, you can make this warning go away by filtering it. To do that, run this code before calling the BeautifulSoup constructor:

    from bs4 import XMLParsedAsHTMLWarning
    import warnings

    warnings.filterwarnings("ignore", category=XMLParsedAsHTMLWarning)

  soup = bs4.BeautifulSoup(line, features="html.parser")

FileURLRetrievalError: Failed to retrieve file url:

	Cannot retrieve the public link of the file. You may need to change
	the permission to 'Anyone with the link', or have had many accesses.
	Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

	https://drive.google.com/uc?id=1pP0XwLrvXGIv3uEXKuc9Ug59soukErEI

but Gdown can't. Please check connections and permissions.