# Day 43 
- PCA , LDA
PCA = Unsupervised
LDA = Supervised

**PCA**
- only input data hercha
- examples price of houses

size of house, no of floor , bathroom , etc (can be more features of house)

feature badi huni vayesi complexity badxa ani accuracy ghatxa

feature kam vaye bhaney 
accuracy badxa complexity ghatxa

steps for PCA 
- mean of every feature
- covriance matrix
- eigen values and vecctors
- choose principle components
- projected data onto principle component


**LDA** 
- LDA is supervised learning primarily used to dimessionality reduction and classification tasks
- The goal is to find a linear combination of features that maximize the seperation of class while minnimizing the spread (variance) within each class.
        - maximizing mean difference
        - minimizing within class scatter

Steps for LDA
 - Calculate the Mean vectors for each class
 - compute the covariance of each class
 - compute the within class scatter matrix
 - compute the between class scatter matrix
 - find eigen vlaues and choose top eigen value
 - find the eigen vectors
 - find the dot product of data points with eigen vector

In [5]:
import pandas as pd
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [7]:
df = sns.load_dataset('titanic')

In [8]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [9]:
X = df[['pclass', 'age', 'sibsp', 'parch', 'fare']]

In [14]:
scalar = StandardScaler()
X = X.fillna(X.mean())
X_Scaled = scalar.fit_transform(X)

In [15]:
pca = PCA(n_components=2)
x_pca = pca.fit_transform(X_Scaled)

In [20]:
pca_df = pd.DataFrame(data=x_pca, columns=['PC1', 'PC2'])
pca_df.head()

        PC1       PC2
0  1.150803 -0.069191
1 -1.758606  0.142885
2  0.889439 -0.718299
3 -1.448581  0.081721
4  0.574460 -0.939013

In [21]:
pca_2 = PCA(n_components=3)

In [22]:
x_pca_1 = pca_2.fit_transform(X_Scaled)

In [23]:
pca_df_1 = pd.DataFrame(data=x_pca_1, columns=['PC1', 'PC2', 'PC3'])
pca_df_1.head()

        PC1       PC2       PC3
0  1.150803 -0.069191 -0.203607
1 -1.758606  0.142885 -0.095648
2  0.889439 -0.718299 -0.210813
3 -1.448581  0.081721 -0.157688
4  0.574460 -0.939013  0.344915

In [27]:
# Applying LDA

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
y= df['survived']

lda = LinearDiscriminantAnalysis(n_components=1)
x_lda = lda.fit_transform(X_Scaled, y)

In [28]:
lda_df = pd.DataFrame(data=x_lda, columns=['LD1'])

In [29]:
lda_df.head()

        LD1
0 -0.782780
1  1.109609
2 -0.712100
3  1.157592
4 -1.092297

- Class work 
 ** Load Iris dataset and perform PCA**
 - Standardize the features.
 - Reduce the dataset from 4D to 2 principal components.
 - Calculate the explained variance ratio.
 - Plot the transformed data using different colors for each species.

In [31]:
df_iris = sns.load_dataset('iris')

In [32]:
df_iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

In [34]:
X_Iris = df_iris[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]

In [36]:
scalar = StandardScaler()
X_Iris = X_Iris.fillna(X_Iris.mean())
X_Iris_Scaled = scalar.fit_transform(X_Iris)

In [37]:
pca = PCA(n_components=2)
x_iris_pca = pca.fit_transform(X_Iris_Scaled)

In [38]:
pca_df = pd.DataFrame(data=x_iris_pca, columns=['PC1', 'PC2'])
pca_df.head()

        PC1       PC2
0 -2.264703  0.480027
1 -2.080961 -0.674134
2 -2.364229 -0.341908
3 -2.299384 -0.597395
4 -2.389842  0.646835

In [ ]:
y= df_iris['petal_length']

lda = LinearDiscriminantAnalysis(n_components=1)
x_lda = lda.fit_transform(X_Iris_Scaled, y)

ValueError: Unknown label type: (array([1.4, 1.4, 1.3, 1.5, 1.4, 1.7, 1.4, 1.5, 1.4, 1.5, 1.5, 1.6, 1.4,
       1.1, 1.2, 1.5, 1.3, 1.4, 1.7, 1.5, 1.7, 1.5, 1. , 1.7, 1.9, 1.6,
       1.6, 1.5, 1.4, 1.6, 1.6, 1.5, 1.5, 1.4, 1.5, 1.2, 1.3, 1.4, 1.3,
       1.5, 1.3, 1.3, 1.3, 1.6, 1.9, 1.4, 1.6, 1.4, 1.5, 1.4, 4.7, 4.5,
       4.9, 4. , 4.6, 4.5, 4.7, 3.3, 4.6, 3.9, 3.5, 4.2, 4. , 4.7, 3.6,
       4.4, 4.5, 4.1, 4.5, 3.9, 4.8, 4. , 4.9, 4.7, 4.3, 4.4, 4.8, 5. ,
       4.5, 3.5, 3.8, 3.7, 3.9, 5.1, 4.5, 4.5, 4.7, 4.4, 4.1, 4. , 4.4,
       4.6, 4. , 3.3, 4.2, 4.2, 4.2, 4.3, 3. , 4.1, 6. , 5.1, 5.9, 5.6,
       5.8, 6.6, 4.5, 6.3, 5.8, 6.1, 5.1, 5.3, 5.5, 5. , 5.1, 5.3, 5.5,
       6.7, 6.9, 5. , 5.7, 4.9, 6.7, 4.9, 5.7, 6. , 4.8, 4.9, 5.6, 5.8,
       6.1, 6.4, 5.6, 5.1, 5.6, 6.1, 5.6, 5.5, 4.8, 5.4, 5.6, 5.1, 5.1,
       5.9, 5.7, 5.2, 5. , 5.2, 5.4, 5.1]),)